### ISSUE TITLE
Add a README

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/telephone#1]
Hey Jen, thanx for working on this (I would like to see it in core of course).

...I'm pretty sure you must be aware of the issue, but there is no README.md:

![backdrop-contrib_modules-telephone-no_info_on_github](https://cloud.githubusercontent.com/assets/2423362/9560578/591edd3e-4e5f-11e5-8f41-24ef12cd68fb.png)

...causing the module to display without any info on b.org:

![backdrop-contrib_modules-telephone-no_info_in_b org](https://cloud.githubusercontent.com/assets/2423362/9560579/6340c1a6-4e5f-11e5-8269-919fa0bdf9a8.png)

**Comment by jackaponte** [comment]
Funnily, the lack of a README made me hesitant to use it until I saw it was ported by @jenlampton! ;)

**Comment by jenlampton** [comment]
Thanks guys!  I'd actually added a readme on my local but never pushed up a branch :/ Pushed now!

**Comment by jackaponte** [comment]
Nice, thanks Jen! 👍
